import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export interface ExportableReport {
  callerNumber: string;
  peakRiskScore: number;
  scamType: string;
  summary: string;
  redFlags: string[];
  formalComplaintText: string;
  investigationStatus?: string;
  investigatorNotes?: string;
  reviewedBy?: string;
  reviewedAt?: string;
  createdAt?: number | string | Date;
}

// ── PDF Export ──
export const exportToPDF = (report: ExportableReport) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 20;

  // Title
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.text('CYBER CRIME INCIDENT REPORT', pageWidth / 2, y, { align: 'center' });
  const titleWidth = doc.getTextWidth('CYBER CRIME INCIDENT REPORT');
  doc.setLineWidth(0.5);
  doc.line((pageWidth - titleWidth) / 2, y + 2, (pageWidth + titleWidth) / 2, y + 2);
  y += 15;

  // Incident Details Table
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.text('Complaint / Incident Details', 14, y);
  y += 5;

  autoTable(doc, {
    startY: y,
    theme: 'grid',
    styles: { fontSize: 10, cellPadding: 3, textColor: [0, 0, 0], lineColor: [0, 0, 0], lineWidth: 0.1 },
    headStyles: { fillColor: [240, 240, 240], fontStyle: 'bold', textColor: [0, 0, 0] },
    columnStyles: { 0: { fontStyle: 'bold', cellWidth: 70 }, 1: { cellWidth: 'auto' } },
    body: [
      ['Date Reported', new Date(report.createdAt || Date.now()).toLocaleString()],
      ['Suspect Caller Number', report.callerNumber],
      ['Category', 'Online Financial Fraud / Scams'],
      ['Sub-Category', report.scamType],
      ['AI Risk Score', `${report.peakRiskScore}/100`],
      ['Investigation Status', report.investigationStatus || 'Pending'],
      ['Reviewed By', report.reviewedBy || '—'],
    ],
  });
  y = (doc as any).lastAutoTable?.finalY ? (doc as any).lastAutoTable.finalY + 10 : y + 50;

  // Red Flags
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.text('Detected Red Flags', 14, y);
  y += 5;

  autoTable(doc, {
    startY: y,
    theme: 'grid',
    styles: { fontSize: 10, cellPadding: 3, textColor: [0, 0, 0], lineColor: [0, 0, 0], lineWidth: 0.1 },
    head: [['#', 'Red Flag']],
    headStyles: { fillColor: [240, 240, 240], fontStyle: 'bold', textColor: [0, 0, 0] },
    columnStyles: { 0: { fontStyle: 'bold', cellWidth: 15 }, 1: { cellWidth: 'auto' } },
    body: report.redFlags.map((flag, i) => [`${i + 1}`, flag]),
  });
  y = (doc as any).lastAutoTable?.finalY ? (doc as any).lastAutoTable.finalY + 10 : y + 30;

  // Summary
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.text('Incident Summary', 14, y);
  y += 6;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  const summaryLines = doc.splitTextToSize(report.summary || 'No summary available.', pageWidth - 28);
  doc.text(summaryLines, 14, y);
  y += summaryLines.length * 5 + 10;

  // Investigation Notes
  if (report.investigatorNotes) {
    if (y > 240) { doc.addPage(); y = 20; }
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.text('Investigator Notes', 14, y);
    y += 6;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    const notesLines = doc.splitTextToSize(report.investigatorNotes, pageWidth - 28);
    doc.text(notesLines, 14, y);
    y += notesLines.length * 5 + 10;
  }

  // Formal Complaint
  if (y > 230) { doc.addPage(); y = 20; }
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.text('Formal Complaint Text (For Police FIR)', 14, y);
  y += 6;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  const complaintLines = doc.splitTextToSize(report.formalComplaintText || 'No complaint text generated.', pageWidth - 28);
  let remaining = [...complaintLines];
  while (remaining.length > 0) {
    const space = 280 - y;
    const fit = Math.floor(space / 5);
    if (fit <= 0) { doc.addPage(); y = 20; continue; }
    doc.text(remaining.slice(0, fit), 14, y);
    remaining = remaining.slice(fit);
    if (remaining.length > 0) { doc.addPage(); y = 20; }
  }

  // Footer on every page
  const pages = doc.getNumberOfPages();
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    doc.setFont('helvetica', 'italic');
    doc.setFontSize(8);
    doc.text(`Generated by GuardCall AI - Page ${i} of ${pages}`, pageWidth / 2, 290, { align: 'center' });
  }

  doc.save(`GuardCall_Investigation_${report.callerNumber}.pdf`);
};

// ── CSV Export ──
export const exportToCSV = (reports: ExportableReport[]) => {
  const headers = ['Caller Number', 'Peak Risk', 'Scam Type', 'Status', 'Reviewer', 'Summary', 'Red Flags', 'Notes'];
  const rows = reports.map((r) => [
    r.callerNumber,
    String(r.peakRiskScore),
    r.scamType,
    r.investigationStatus || 'Pending',
    r.reviewedBy || '',
    `"${(r.summary || '').replace(/"/g, '""')}"`,
    `"${r.redFlags.join('; ')}"`,
    `"${(r.investigatorNotes || '').replace(/"/g, '""')}"`,
  ]);

  const csv = [headers.join(','), ...rows.map((r) => r.join(','))].join('\n');
  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `GuardCall_Cases_${new Date().toISOString().slice(0, 10)}.csv`;
  a.click();
  URL.revokeObjectURL(url);
};

// ── HTML Export ──
export const exportToHTML = (report: ExportableReport) => {
  const riskColor = report.peakRiskScore >= 70 ? '#E24B4A' : report.peakRiskScore >= 40 ? '#EF9F27' : '#1D9E75';
  const statusColor =
    report.investigationStatus === 'Verified' ? '#1D9E75'
    : report.investigationStatus === 'Suspected' ? '#E24B4A'
    : '#EF9F27';

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>GuardCall Incident Report - ${report.callerNumber}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { background: #0D1B2A; color: #E8E6E1; font-family: 'Segoe UI', system-ui, sans-serif; padding: 40px 20px; }
    .container { max-width: 800px; margin: 0 auto; }
    .header { text-align: center; margin-bottom: 32px; padding-bottom: 20px; border-bottom: 2px solid #1D9E75; }
    .header h1 { font-size: 24px; letter-spacing: 2px; color: #1D9E75; margin-bottom: 8px; }
    .header p { color: rgba(232, 230, 225, 0.5); font-size: 13px; }
    .card { background: rgba(255, 255, 255, 0.04); border: 1px solid rgba(255, 255, 255, 0.08); border-radius: 12px; padding: 20px; margin-bottom: 16px; }
    .card h2 { font-size: 14px; text-transform: uppercase; letter-spacing: 1px; color: rgba(232, 230, 225, 0.5); margin-bottom: 12px; }
    .stats { display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 12px; margin-bottom: 16px; }
    .stat { background: rgba(255, 255, 255, 0.06); border-radius: 8px; padding: 16px; text-align: center; }
    .stat .label { font-size: 11px; text-transform: uppercase; color: rgba(232, 230, 225, 0.4); margin-bottom: 6px; }
    .stat .value { font-size: 20px; font-weight: 700; }
    .badge { display: inline-block; padding: 4px 12px; border-radius: 999px; font-size: 12px; font-weight: 600; }
    .flag { padding: 10px 14px; border-left: 3px solid #E24B4A; background: rgba(226, 75, 74, 0.08); border-radius: 0 8px 8px 0; margin-bottom: 8px; font-size: 14px; }
    .complaint { background: #09121c; border: 1px solid rgba(255, 255, 255, 0.05); border-radius: 8px; padding: 20px; font-family: monospace; font-size: 13px; color: rgba(232, 230, 225, 0.6); white-space: pre-wrap; line-height: 1.7; }
    .footer { text-align: center; margin-top: 32px; padding-top: 16px; border-top: 1px solid rgba(255, 255, 255, 0.08); color: rgba(232, 230, 225, 0.3); font-size: 12px; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>CYBER CRIME INCIDENT REPORT</h1>
      <p>Generated on ${new Date().toLocaleString()} by GuardCall AI</p>
    </div>

    <div class="stats">
      <div class="stat">
        <div class="label">Caller Number</div>
        <div class="value" style="font-family: monospace; font-size: 16px;">${report.callerNumber}</div>
      </div>
      <div class="stat">
        <div class="label">Peak Risk Score</div>
        <div class="value" style="color: ${riskColor};">${report.peakRiskScore}/100</div>
      </div>
      <div class="stat">
        <div class="label">Scam Type</div>
        <div class="value" style="font-size: 14px;">${report.scamType}</div>
      </div>
    </div>

    <div class="card">
      <h2>Investigation Status</h2>
      <span class="badge" style="background: ${statusColor}22; color: ${statusColor};">${report.investigationStatus || 'Pending'}</span>
      ${report.reviewedBy ? `<span style="margin-left: 12px; color: rgba(232,230,225,0.5); font-size: 13px;">Reviewed by: ${report.reviewedBy}</span>` : ''}
    </div>

    <div class="card">
      <h2>Summary</h2>
      <p style="line-height: 1.7; font-size: 14px;">${report.summary}</p>
    </div>

    <div class="card">
      <h2>Detected Red Flags</h2>
      ${report.redFlags.map((f) => `<div class="flag">${f}</div>`).join('')}
    </div>

    ${report.investigatorNotes ? `<div class="card"><h2>Investigator Notes</h2><p style="line-height: 1.7; font-size: 14px;">${report.investigatorNotes}</p></div>` : ''}

    <div class="card">
      <h2>Formal Complaint Text (Police FIR)</h2>
      <div class="complaint">${report.formalComplaintText}</div>
    </div>

    <div class="footer">Generated by GuardCall AI &bull; Confidential</div>
  </div>
</body>
</html>`;

  const blob = new Blob([html], { type: 'text/html;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `GuardCall_Report_${report.callerNumber}.html`;
  a.click();
  URL.revokeObjectURL(url);
};
