import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

// Fix TS type for autoTable since it's a plugin
interface jsPDFWithPlugin extends jsPDF {
  lastAutoTable: { finalY: number };
}

export interface ReportData {
  callerNumber: string;
  peakRiskScore: number;
  scamType: string;
  summary: string;
  redFlags: string[];
  formalComplaintText: string;
  createdAt?: number | string | Date;
}

export const generatePDFReport = (reportData: ReportData) => {
  const doc = new jsPDF() as jsPDFWithPlugin;
  
  // Page setup
  const pageWidth = doc.internal.pageSize.getWidth();
  let currentY = 20;

  // Header Title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text("CYBER CRIME INCIDENT REPORT", pageWidth / 2, currentY, { align: "center" });
  
  // Underline for title
  const textWidth = doc.getTextWidth("CYBER CRIME INCIDENT REPORT");
  doc.setLineWidth(0.5);
  doc.line((pageWidth - textWidth) / 2, currentY + 2, (pageWidth + textWidth) / 2, currentY + 2);
  currentY += 15;

  // Incident Overview Table
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text("Complaint / Incident Details", 14, currentY);
  currentY += 5;

  autoTable(doc, {
    startY: currentY,
    theme: 'grid',
    styles: { fontSize: 10, cellPadding: 3, textColor: [0, 0, 0], lineColor: [0, 0, 0], lineWidth: 0.1 },
    headStyles: { fillColor: [240, 240, 240], fontStyle: 'bold', textColor: [0, 0, 0] },
    columnStyles: {
      0: { fontStyle: 'bold', cellWidth: 70 },
      1: { cellWidth: 'auto' }
    },
    body: [
      ['Date Reported', new Date(reportData.createdAt || Date.now()).toLocaleString()],
      ['Suspect Caller Number', reportData.callerNumber],
      ['Category of complaint', 'Online Financial Fraud / Scams'],
      ['Sub-Category of complaint', reportData.scamType],
      ['AI Risk Assessment Score', `${reportData.peakRiskScore}/100`],
    ],
  });

  currentY = (doc as any).lastAutoTable?.finalY ? (doc as any).lastAutoTable.finalY + 10 : currentY + 40;

  // Red Flags Detected Table
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text("Detected Red Flags / Manipulation Tactics", 14, currentY);
  currentY += 5;

  autoTable(doc, {
    startY: currentY,
    theme: 'grid',
    styles: { fontSize: 10, cellPadding: 3, textColor: [0, 0, 0], lineColor: [0, 0, 0], lineWidth: 0.1 },
    head: [['#', 'Red Flag Description']],
    headStyles: { fillColor: [240, 240, 240], fontStyle: 'bold', textColor: [0, 0, 0] },
    columnStyles: {
      0: { fontStyle: 'bold', cellWidth: 15 },
      1: { cellWidth: 'auto' }
    },
    body: reportData.redFlags.map((flag, index) => [`${index + 1}`, flag]),
  });

  currentY = (doc as any).lastAutoTable?.finalY ? (doc as any).lastAutoTable.finalY + 15 : currentY + 15;

  // Incident Summary
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text("Incident Summary", 14, currentY);
  currentY += 6;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  
  const summaryLines = doc.splitTextToSize(reportData.summary || 'No summary available.', pageWidth - 28);
  doc.text(summaryLines, 14, currentY);
  currentY += (summaryLines.length * 5) + 10;

  // Check Page break before FIR
  if (currentY > 230) {
    doc.addPage();
    currentY = 20;
  }

  // Formal Complaint Text
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text("Formal Complaint Text (For Police FIR)", 14, currentY);
  currentY += 6;
  
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  
  const complaintLines = doc.splitTextToSize(reportData.formalComplaintText || 'No complaint text generated.', pageWidth - 28);
  
  let remainingLines = [...complaintLines];
  while (remainingLines.length > 0) {
    const spaceLeft = 280 - currentY;
    const linesThatFit = Math.floor(spaceLeft / 5);
    
    if (linesThatFit <= 0) {
      doc.addPage();
      currentY = 20;
      continue;
    }
    
    const linesToDraw = remainingLines.slice(0, linesThatFit);
    doc.text(linesToDraw, 14, currentY);
    
    remainingLines = remainingLines.slice(linesThatFit);
    if (remainingLines.length > 0) {
      doc.addPage();
      currentY = 20;
    }
  }

  // Footer on all pages
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFont("helvetica", "italic");
    doc.setFontSize(8);
    doc.text(
      `Generated by GuardCall AI - Page ${i} of ${pageCount}`,
      pageWidth / 2,
      290,
      { align: "center" }
    );
  }
  
  doc.save(`Cyber_Crime_Incident_${reportData.callerNumber}.pdf`);
};
