import React from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import { motion, Variants } from 'framer-motion';
import { ShieldAlert, FileDown, ExternalLink, Users, AlertTriangle, Hash, Activity, Home, Copy, CheckCircle } from 'lucide-react';
import { generatePDFReport, ReportData } from '../services/reportPDF';

const ReportView: React.FC = () => {
  const location = useLocation();
  const navigate = useNavigate();
  const report = location.state?.report as ReportData;
  const [copied, setCopied] = React.useState(false);

  if (!report) {
    return (
      <div className="min-h-screen bg-background flex items-center justify-center">
        <p className="text-white/50">No report data found. Returning home...</p>
        {setTimeout(() => navigate('/'), 2000) && null}
      </div>
    );
  }

  const containerVariants: Variants = {
    hidden: { opacity: 0 },
    show: {
      opacity: 1,
      transition: { staggerChildren: 0.1 }
    }
  };

  const itemVariants: Variants = {
    hidden: { opacity: 0, y: 20 },
    show: { opacity: 1, y: 0, transition: { type: "spring", stiffness: 300, damping: 24 } }
  };

  const handleCopyFIR = () => {
    navigator.clipboard.writeText(report.formalComplaintText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="min-h-screen bg-background text-text p-4 pb-24 max-w-2xl mx-auto">
      {/* Header */}
      <motion.div 
        initial={{ opacity: 0, scale: 0.9 }} 
        animate={{ opacity: 1, scale: 1 }} 
        className="flex flex-col items-center justify-center text-center mt-6 mb-8"
      >
        <div className="w-16 h-16 bg-danger/20 rounded-2xl flex items-center justify-center mb-4 border border-danger/30 shadow-[0_0_30px_rgba(226,75,74,0.2)]">
          <ShieldAlert className="w-8 h-8 text-danger" />
        </div>
        <h1 className="text-3xl font-bold text-white mb-1 tracking-tight">Incident Report</h1>
        <p className="text-white/50 text-sm">Auto-generated by GuardCall AI</p>
      </motion.div>

      <motion.div 
        variants={containerVariants} 
        initial="hidden" 
        animate="show"
        className="space-y-4"
      >
        {/* Quick Stats Grid */}
        <motion.div variants={itemVariants} className="grid grid-cols-2 gap-3">
          <div className="glass-card p-4 flex flex-col">
            <span className="text-white/40 text-[10px] uppercase tracking-wider mb-2 flex items-center gap-1">
              <Hash className="w-3 h-3" /> Caller
            </span>
            <span className="font-mono text-lg text-white font-medium">{report.callerNumber}</span>
          </div>
          <div className="glass-card p-4 flex flex-col">
            <span className="text-white/40 text-[10px] uppercase tracking-wider mb-2 flex items-center gap-1">
              <Activity className="w-3 h-3" /> Peak Risk
            </span>
            <span className="text-2xl font-bold text-danger leading-none">{report.peakRiskScore}<span className="text-sm text-danger/60 font-normal">/100</span></span>
          </div>
        </motion.div>

        {/* Summary Card */}
        <motion.div variants={itemVariants} className="glass-card-strong p-5 relative overflow-hidden">
          <div className="absolute top-0 left-0 w-1 h-full bg-warning" />
          <div className="inline-block px-3 py-1 bg-warning/20 text-warning text-xs font-bold rounded-full uppercase tracking-wide mb-3">
            {report.scamType}
          </div>
          <p className="text-white/90 leading-relaxed text-sm">
            {report.summary}
          </p>
        </motion.div>

        {/* Red Flags */}
        <motion.div variants={itemVariants}>
          <h3 className="text-sm font-bold text-white/70 uppercase tracking-widest mb-3 ml-2 mt-6">Detected Red Flags</h3>
          <div className="space-y-2">
            {report.redFlags.map((flag, idx) => (
              <div key={idx} className="glass-card p-3 px-4 flex gap-3 items-start border-l-2 border-l-danger/50">
                <AlertTriangle className="w-4 h-4 text-danger shrink-0 mt-0.5" />
                <span className="text-sm text-white/80">{flag}</span>
              </div>
            ))}
          </div>
        </motion.div>

        {/* FIR Template */}
        <motion.div variants={itemVariants}>
          <h3 className="text-sm font-bold text-white/70 uppercase tracking-widest mb-3 ml-2 mt-6">Cyber Police FIR Template</h3>
          <div className="relative group">
            <div className="bg-[#09121c] border border-white/5 rounded-xl p-5 text-sm text-white/60 font-mono leading-relaxed whitespace-pre-wrap selection:bg-primary/30">
              {report.formalComplaintText}
            </div>
            <button 
              onClick={handleCopyFIR}
              className="absolute top-3 right-3 p-2 bg-white/10 hover:bg-white/20 rounded-lg backdrop-blur-md transition-all text-white"
              title="Copy to clipboard"
            >
              {copied ? <CheckCircle className="w-4 h-4 text-primary" /> : <Copy className="w-4 h-4" />}
            </button>
          </div>
        </motion.div>

        {/* Action Buttons */}
        <motion.div variants={itemVariants} className="pt-8 space-y-3 pb-8">
          <button 
            onClick={() => generatePDFReport(report)}
            className="w-full py-3.5 px-4 bg-gradient-to-r from-primary to-primary-light hover:from-primary-light hover:to-primary text-white rounded-xl font-bold shadow-[0_0_20px_rgba(29,158,117,0.3)] transition-all flex items-center justify-center gap-2 active:scale-[0.98]"
          >
            <FileDown className="w-5 h-5" />
            Download PDF Report
          </button>
          
          <button 
            onClick={() => window.open('https://sancharsaathi.gov.in', '_blank')}
            className="w-full py-3.5 px-4 bg-transparent border border-white/20 hover:border-white/40 hover:bg-white/5 text-white rounded-xl font-medium transition-all flex items-center justify-center gap-2 active:scale-[0.98]"
          >
            <ExternalLink className="w-5 h-5 text-white/60" />
            Report to Sanchar Saathi
          </button>

          <button 
            className="w-full py-3.5 px-4 bg-white/5 hover:bg-white/10 text-white rounded-xl font-medium transition-all flex items-center justify-center gap-2 active:scale-[0.98] mt-2"
          >
            <Users className="w-5 h-5 text-white/60" />
            Submit to Community Database
          </button>
        </motion.div>
        
        {/* Back home */}
        <motion.div variants={itemVariants} className="text-center">
          <button 
            onClick={() => navigate('/')}
            className="text-white/40 hover:text-white flex items-center justify-center gap-2 mx-auto text-sm transition-colors py-4"
          >
            <Home className="w-4 h-4" /> Return to Home
          </button>
        </motion.div>

      </motion.div>
    </div>
  );
};

export default ReportView;
